### ISSUE TITLE
Import fails in 0.16.2 (Cannot read property 'forEach' of undefined)

### ISSUE THREAD

**Issue by beevelop** [botfront/botfront#257]
Experimenting with the new 0.16.2 release, we experienced the following issue: When we tried to import an existing Rasa NLU definition, the UI responds with a red `Error: [Object object]`. The websocket response itself reveals, that this might be due to a coding issue:
```
0: "{"msg":"result","id":"3","error":{"isClientSafe":true,"error":{},"message":"[TypeError: Cannot read property 'forEach' of undefined]","errorType":"Meteor.Error"}}"
```

According to the changelogs, there were quite some changes to the import feature, so my guess is that this bug slipped in some way.

**Comment by pheel** [comment]
Hi @beevelop thanks for catching this.
Fixed on master: https://github.com/botfront/botfront/commit/abd0b4bce1ba1c35b5e7c39205bb1f8a46a81c4d

**Comment by martinavalogia** [comment]
https://share.getcloudapp.com/llunyeJ0

I am still getting this error
